[variables]
NIXPACKS_NODE_VERSION = "20"
NPM_CONFIG_FUND = "false"
NPM_CONFIG_AUDIT = "false"

[phases.install]
cmds = [
  "npm install --no-audit --no-fund",
  "npm install --prefix server --no-audit --no-fund",
  "npm install --prefix client --no-audit --no-fund"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
